---

version: '3'

vars:
  BUILD_DATE:
    sh: date +"%Y%m%d-%H%M%S"

tasks:
  build:
    cmds:
      - >-
        docker build . \
          -t agrrh/day-to-remember:dev-tg-bot

  push:
    deps:
      - build
    cmds:
      - >-
        docker build . \
          -t agrrh/day-to-remember:dev-{{.BUILD_DATE}} \
          --push
